baseurl = "https://sebviolet.github.io/hugo-theme-terminal-sebos/"
languageCode = "en-us"
#theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Blog Perso"
    copyright = "sebos"

    [languages.en.params]
      readOtherPosts = "Read other posts"
      subtitle = "A simple, retro theme for Hugo"
      keywords = ""
      menuMore = "Show more"
      readMore = "Read more"
      logoText = "Blog Perso"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "lespirtates"
        name = "Les Pirates"
        url = "/lespirates"

      [[languages.en.menu.main]]
        identifier = "lesavengers"
        name = "Les Avengers"
        url = "/lesavengers"
