baseurl = "https://sebviolet.github.io/hugo-theme-terminal-sebos/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Terminal"
    copyright = ""

    [languages.en.params]
      readOtherPosts = "Read other posts"
      subtitle = "A simple, retro theme for Hugo"
      keywords = ""
      menuMore = "Show more"
      readMore = "Read more"
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
